restaurent/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from website.views import Index

urlpatterns = [ 
    url(r'^admin/', admin.site.urls),
    url(r'^$',Index.as_view(),name='index'),
    url(r'^Olessia/', include('website.urls', namespace='website_url')),
]

website/urls.py
from django.conf.urls import url
from website import views

urlpatterns = [ 
    url(r'^rooms/$',views.Events.as_view(),name='events'),
    url(r'^about_us/$',views.Aboutus.as_view(),name='about_us'),
    url(r'^contact_us/$',views.Contact.as_view(),name='contact_us'),
    url(r'^rooms/$',views.Rooms.as_view(),name='rooms'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class Index(View):
    def get(self,request):
        return render(request,"web/website/index.html",{})

class Aboutus(View):
    def get(self,request):
        return render(request,"web/website/about.html")

class Events(View):
    def get(self,request):
        return render(request,"web/website/events.html",{})

class Contact(View): 
    def get(self,request):
        return render(request,"web/website/contact.html",{})  

class Rooms(View): 
    def get(self,request): 
        return render(request,"web/website/rooms.html",{})                


templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
  <head> 
    <title>Olessia &mdash; Hotel & Restaurent </title> 
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Work+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/mediaelementplayer.min.css">
    
    
    
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
  </head>
  <body>
      {% block content %}
      {% endblock %}
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
      <script src="{% static 'js/jquery-ui.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
      <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
      <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script> 
      <script src="{% static 'js/aos.js' %}"></script>
    
      
      <script src="{% static 'js/mediaelement-and-player.min.js' %}"></script>
    
      <script src="{% static 'js/main.js' %}"></script>
        
    
      <script>
          document.addEventListener('DOMContentLoaded', function() {
                    var mediaElements = document.querySelectorAll('video, audio'), total = mediaElements.length;
    
                    for (var i = 0; i < total; i++) {
                        new MediaElementPlayer(mediaElements[i], {
                            pluginPath: 'https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/',
                            shimScriptAccess: 'always',
                            success: function () {
                                var target = document.body.querySelectorAll('.player'), targetTotal = target.length;
                                for (var j = 0; j < targetTotal; j++) {
                                    target[j].style.visibility = 'visible';
                                }
                      }
                    });
                    }
                });
        </script>
  {% block javascript %}
  {% endblock %}      
  </body>
  </html>

templates/web/common/footer.html
<footer class="site-footer">
    <div class="container">
      

      <div class="row">
        <div class="col-md-4">
          <h3 class="footer-heading mb-4 text-white">About</h3>
          <p>Our hotel like Metro front city hotel offers Luxury touches that echo the
            essence of what you want as a traveller comfort, service and beauty for all five senses.The Olessia Hotel features 3 Deluxe Rooms and 26 Standard Rooms.</p>
          <p><a href="{% url 'website_url:about_us' %}" class="btn btn-primary pill text-white px-4">Read More</a></p>
        </div>
<!--         <div class="col-md-6">
          <div class="row"> 
            <div class="col-md-6">
              <h3 class="footer-heading mb-4 text-white">Quick Menu</h3>
                <ul class="list-unstyled">
                  <li><a href="#">About</a></li>
                  <li><a href="#">Services</a></li>
                  <li><a href="#">Approach</a></li>
                  <li><a href="#">Sustainability</a></li>
                  <li><a href="#">News</a></li>
                  <li><a href="#">Careers</a></li>
                </ul>
            </div>
            <div class="col-md-6">
              <h3 class="footer-heading mb-4 text-white">Ministries</h3>
                <ul class="list-unstyled">
                  <li><a href="#">Children</a></li>
                  <li><a href="#">Women</a></li>
                  <li><a href="#">Study</a></li>
                  <li><a href="#">Church</a></li>
                  <li><a href="#">Mosque</a></li>
                  <li><a href="#">Temple</a></li>
                </ul>
            </div>
          </div>
        </div> -->

        
        <div class="col-md-2">
          <div class="col-md-12"><h3 class="footer-heading mb-4 text-white">Social Icons</h3></div>
            <div class="col-md-12">
              <p>
                <a href="https://www.facebook.com/olessia123" class="pb-2 pr-2 pl-0"><span class="icon-facebook"></span></a>
                <a href="https://twitter.com/HotelOlessia" class="p-2"><span class="icon-twitter"></span></a>
                <a href="https://www.instagram.com/olessia_hotel/?hl=en" class="p-2"><span class="icon-instagram"></span></a>
                <a href="#" class="p-2"><span class="icon-vimeo"></span></a>

              </p>
            </div>
        </div>
      </div>
      <!-- <div class="row pt-5 mt-5 text-center">
        <div class="col-md-12">
          <p>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          <!-- Copyright &copy; <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All Rights Reserved | This template is made with <i class="icon-heart text-primary" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
        
      </div>
    </div>
  </footer>

templates/web/common/header.html
<div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div> 
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu --> 
    
    
    <div class="site-navbar-wrap js-site-navbar bg-white">
      
      <div class="container">
        <div class="site-navbar bg-light">
          <div class="py-1">
            <div class="row align-items-center">
              <div class="col-2">
                <h2 class="mb-0 site-logo"><a href="{% url 'index' %}">Olessia</a></h2>
              </div>
              <div class="col-10">
                <nav class="site-navigation text-right" role="navigation">
                  <div class="container">
                    
                    <div class="d-inline-block d-lg-none  ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu h3"></span></a></div>
                    <ul class="site-menu js-clone-nav d-none d-lg-block">
                      <li>
                        <a href="{% url 'index' %}">Home</a>
                      </li>
                      <li class="has-children active">
                        <a href="#">Rooms</a>
                        <ul class="dropdown arrow-top">
                          <li><a href="#">Standard Room</a></li>
                          <li><a href="#">Deluxe Room</a></li>
                          <!-- <li class="has-children">
                            <a href="rooms.html">Rooms</a>
                            <ul class="dropdown">
                              <li><a href="rooms.html">America</a></li>
                              <li><a href="rooms.html">Europe</a></li>
                              <li><a href="rooms.html">Asia</a></li>
                              <li><a href="rooms.html">Africa</a></li>
                              
                            </ul>
                          </li> -->

                        </ul>
                      </li>
                      <li><a href="{% url 'website_url:events' %}">Events</a></li>
                      <li><a href="{% url 'website_url:about_us' %}">About</a></li>
                      <li><a href="{% url 'website_url:contact_us' %}">Contact</a></li>
                    </ul> 
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

templates/web/website/about.html
{% extends "../base.html" %}
{% block content %}
{% load static %}
{% include "../common/header.html" %}      
    <div class="site-blocks-cover overlay" style="background-image: url({% static 'images/kochi.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center"> 
            <div class="col-md-7 text-center" data-aos="fade">
              <span class="caption mb-3">Suites Hotel &amp; Restaurent</span>
              <h1 class="mb-4">About Us</h1>
            </div>
          </div>
        </div>
      </div>  
 
    
    <div class="site-section">
      <div class="container">
        <div class="row align-items-center">
          <!-- <div class="col-md-6 mb-5 mb-md-0">
            
              <div class="img-border">
                <a href="https://vimeo.com/28959265" class="popup-vimeo image-play">
                  <span class="icon-wrap">
                    <span class="icon icon-play"></span>
                  </span>
                  <img src="{% static 'images/img_2.jpg' %}" alt="" class="img-fluid">
                </a>
              </div>

              <img src="{% static 'images/img_1.jpg' %}" alt="Image" class="img-fluid image-absolute">
            
          </div>  -->
          <div class="col-md-5 ml-auto">
            

            <div class="section-heading text-left">
              <h2 class="mb-5">About Us</h2>
            </div>
            <p class="mb-4">Our hotel like Metro front city hotel offers Luxury touches that echo the
            essence of what you want as a traveler comfort, service and beauty for all five senses.The Olessia Hotel features 3 Deluxe Rooms and 26 Standard Rooms.Every facility required for comfortable living on hand.From the Door man and the Resident services desk that warmly greet the guest  and remain committed to provide with state of art facilities.<br>
            Olessia Hotel Ernakulam located in the prestige central business district of Kerala, Cochin.
            Just step away from major Metro Station,Railway Station and Bus stand.While the Javaharlal Nehru Stadium  near 500 m drive away,Fort Kochi 17km,Lulu Mall 4km and Cochin International Airport 26 km drive away from here....
            For more inquiry please email us @ <a href="#">reservation@olessiahotel.com</a> or call us @ <a href="#">+91484 4853888</a>
              </p>
          </div>
        </div>
      </div>
    </div>


<!--     <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Hotel Staffs</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid"></a>
              <div class="p-4">
                <h3 class="heading mb-3"><a href="#">Angella Lopez</a></h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
                <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="{% static 'images/person_2.jpg' %}" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Marina Stalks</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="{% static 'images/person_3.jpg' %}" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Ethan Hoover</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="{% static 'images/person_4.jpg' %}" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Megan Pearson</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Cristine Smith</a></h3> 
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="{% static 'images/person_2.jpg' %}" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Marina Stalks</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> -->


    <!-- <div class="py-5 upcoming-events" style="background-image: url({% static 'images/hero_1.jpg' %}); background-attachment: fixed;">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <h2 class="text-white">Summer Promo 50% Off</h2>
            <a href="#" class="text-white btn btn-outline-warning rounded-0 text-uppercase">Avail Now</a>
          </div>
          <div class="col-md-6">
            <span class="caption">The Promo will start in</span>
            <div id="date-countdown"></div>    
          </div>
        </div>
        
      </div>
    </div> -->
  

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Hotel Features</h2>
          </div>
        </div> 
        <div class="row">
<!--           <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-pool display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Swimming Pool</h2>
            </div>
          </div> -->
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-desk display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Hotel Teller</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-exit display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Fire Exit</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-parking display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Car Parking</h2>
            </div>
          </div>

<!--           <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-hair-dryer display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Hair Dryer</h2>
            </div>
          </div> -->

          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-drink display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Restaurent</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-minibar display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Hot Water</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-tv display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">LED TV 32</h2>
            </div>
          </div>
<!--           <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-drink display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Drinks</h2>
            </div>
          </div> -->
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-cab display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Car Airport</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <!-- <span class="flaticon-tray display-3 mb-3 d-block text-primary"> -->
              <img width="100" heigh="100" src="{% static 'images/icons/wifi.png' %}">
              <h2 class="h5">Free WIFI</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <!-- <span class="flaticon-tray display-3 mb-3 d-block text-primary"></span>-->
              <img width="100" heigh="100" src="{% static 'images/icons/two-shirt.png' %}">
            <h2 class="h5">Laundry</h2>
            </div>
          </div>

          

          

          

        </div>
      </div>
    </div>


    <div class="site-section border-top">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Our Gallery</h2>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="row no-gutters">
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/deluxe rooms/deluxeroom1.jpeg' %}" class="image-popup img-opacity"><img src="{% static 'images/deluxe rooms/deluxeroom1.jpeg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o14.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o14.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/deluxe rooms/deluxeroom4.jpeg' %}" class="image-popup img-opacity"><img src="{% static 'images/deluxe rooms/deluxeroom4.jpeg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o19.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o19.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>

          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o16.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o16.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o15.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o15.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o9.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o9.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o18.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o18.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>

          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o5.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o5.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="{% static 'images/olessia/o6.jpg' %}" class="image-popup img-opacity"><img src="{% static 'images/olessia/o6.jpg' %}" alt="Image" class="img-fluid"></a>
          </div>

        </div>
      </div>
    </div>
  </div>
  {% include '../common/footer.html' %}  
  {% endblock %} 

templates/web/website/contact.html
{% extends "../base.html" %}
{% block content %}
{% load static %}
{% include "../common/header.html" %}     
    <div class="site-blocks-cover overlay" style="background-image: url({% static 'images/contact_us.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7 text-center" data-aos="fade">
              <span class="caption mb-3">Chat With Us</span>
              <h1 class="mb-4">Get In Touch</h1>
            </div>
          </div>
        </div>
      </div>    

    
    <div class="site-section site-section-sm">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
            
          
            <form action="#" class="p-5 bg-white">

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Full Name</label>
                  <input type="text" id="fullname" class="form-control" placeholder="Full Name">
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <label class="font-weight-bold" for="email">Email</label>
                  <input type="email" id="email" class="form-control" placeholder="Email Address">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="phone">Phone</label>
                  <input type="text" id="phone" class="form-control" placeholder="Phone #">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="font-weight-bold" for="message">Message</label> 
                  <textarea name="message" id="message" cols="30" rows="5" class="form-control" placeholder="Say hello to us"></textarea>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Send Message" class="btn btn-primary pill px-4 py-2">
                </div>
              </div>

  
            </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">Olessia Hotel - Near Lenin Center <br>  Kaloor - Cochin <br> Pin :682017</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+91484 4853888</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">reservation@olessiahotel.com</a></p>

            </div>
            
            
          </div>
        </div>
      </div>
    </div> 
  </div>
{% include '../common/footer.html' %}  
{% endblock %}  